### ISSUE TITLE
Invalid artifact tag is ignored

### ISSUE THREAD

**Issue by electrum** [jvanzyl/provisio#27]
There was no error for the `<delete>` tag which should have been inside `<alter>`.

```xml
<runtime>
    <artifactSet to="/">
        <artifact id="io.prestosql:presto-server:tar.gz:${dep.presto.version}">
            <unpack dereferenceHardlinks="true" useRoot="false" />
            <exclude dir="plugin/hive-hadoop2" />
            <delete>
                <file path="lib/presto-main-${dep.presto.version}.jar" />
            </delete>
        </artifact>
    </artifactSet>
</runtime>
```

**Comment by electrum** [comment]
This is on 1.0.7 so this might be fixed already.

**Comment by jvanzyl** [comment]
Yup, it's fixed here:

https://github.com/jvanzyl/provisio/commit/dae7883e33ac532d9decf3ab7f28739cf8605b32

And tests are here:

https://github.com/jvanzyl/provisio/blob/master/provisio-model/src/test/java/ca/vanzyl/provisio/model/RuntimeReaderTest.java#L320
