### ISSUE TITLE
Possible to refer to archives built in other modules?

### ISSUE THREAD

**Issue by helpermethod** [jvanzyl/provisio#32]
Hi,

I have the following problem:

Project A creates a ZIP archive with a Graal Native Image included

Now, the idea is that project B takes that archive and unpacks it in its runtime descriptor. But how to refer to the ZIP archive created in Project A?

Is this possible at all?

Thanks in advance!

**Comment by hashhar** [comment]
Yes, this is possible as long as the archive is attached to the module output. You can then refer to it using a type/classifier (or both) in the provisio manifest.

```xml
<runtime>
    <!-- Bring server tar.gz over for the RPM -->
    <artifactSet to="/">
        <artifact id="${project.groupId}:moduleA:zip:x86_64:${project.version}">
            <unpack />
        </artifact>
    </artifactSet>
</runtime>
```

The `moduleA`'s pom needs to attach the artifacts as `<type>zip</type> <classifier>x86_64</classifier>` in this example.
